### PR TITLE
Ebml schema refactor

### PR DESCRIPTION
**Pull request by dericed**
This PR follows upon https://mailarchive.ietf.org/arch/msg/cellar/kvKt9FagzziL94tNfF0Itye83HA. Please review.

### CODE REVIEW

**Comment by mbunkus** [comment]
I've reviewed the commits and left my notes as line notes.

**Comment by dericed** [comment]
Unfortunately the squashing seems to have lost @mbunkus initial comments. Here's a summary of what I just did:
- in maxOccurs definition say it is the number of occurrences that MAY occur (was MUST before)
- switch lang tag in EBML Schema documentation to use RFC 5646
- remove accidental line breaks
- grammar suggestions on the arrangement of <element> nodes in an EBML Schema
- remove unneeded maxOccurs from the EBML Schema example

Should be ready for a re-review.

**Comment by dericed** [comment]
Updated with minver and maxver attributes for EBML Schema. Updated to say that the EBML Schema doesn't document the EBML Header. Add a version attribute to EBML Schema. See also: https://mailarchive.ietf.org/arch/msg/cellar/yXQSR2dfT4ytUvc7JcD_eZzeb7w.

**Comment by mbunkus** [comment]
I've added all the comments that I could think of for the push from Feb 9. Apart from those it looks good to me.

**Comment by dericed** [comment]
Fixes according to the current comments here are in https://github.com/MediaArea/ebml-specification/commit/cd1c54b54417c0fc07746e651d8c0bf2e3bbdf40. Should I squash?

**Comment by mbunkus** [comment]
Yes, please. I'll merge afterwards.

**Comment by dericed** [comment]
done

**Comment by mbunkus** [comment]
Thanks.

**Pull request merged**
