### PR TITLE
docType should not be empty

### PR DESCRIPTION
**Pull request by dericed**

### CODE REVIEW

**Comment by robUx4** [comment]
Do we want a max size ?
Maybe someday the doctype may be extended with more subtle uses like extensions and such.

**Comment by dericed** [comment]
I initially had it as `>0`. I could put that back.

**Comment by dericed** [comment]
Ok, back at `>0`.

**Comment by dericed** [comment]
Should this be merged or closed? Can an empty string be `A string that describes and identifies the content of the EBML Body that follows this EBML Header`?

**Pull request merged**
