### PR TITLE
Show the EBML IDs range

### PR DESCRIPTION
**Pull request by robUx4**
This is clearer and safer to compute the amount of values.

Replaces #227

### CODE REVIEW

**Comment by mkver** [comment]
Your table is wrong: 0x4001, 0x200001 and 0x10000001 are not coded on the least number of octets possible, hence they are invalid IDs. The real table is

Your table is wrong: 0x4001, 0x200001 and 0x10000001 are not coded on the least number of octets possible, hence they are invalid IDs (and classes B-D are off by one even if we ignore that). The real table is:
```
Class A: 0x81 to 0xFE = 126
Class B: 0x407F to 0x7FFE = 16,256
Class C: 0x203FFF to 0x3FFFFE = 2,080,768
Class D: 0x101FFFFF to 0x1FFFFFFE = 266,338,304
```

Also, what's the point of adding my commit to this PR if you intend to replace it with something completely different?

**Comment by dericed** [comment]
Maybe I'm forgetting a rule, but wouldn't the lower limits be 0x4040, 0x202000 and 0x10100000?

As in:

```
Class A:       0x81 to 0xFE       =         126
Class B:     0x4040 to 0x7FFE     =      16,319
Class C:   0x202000 to 0x3FFFFE   =   2,088,959
Class D: 0x10100000 to 0x1FFFFFFE = 267,386,879
```

**Comment by robUx4** [comment]
> Your table is wrong: 0x4001, 0x200001 and 0x10000001 are not coded on the least number of octets possible, hence they are invalid IDs (and classes B-D are off by one even if we ignore that). The real table is:
> 
> ```
> Class A: 0x81 to 0xFE = 126
> Class B: 0x407F to 0x7FFE = 16,256
> Class C: 0x203FFF to 0x3FFFFE = 2,080,768
> Class D: 0x101FFFFF to 0x1FFFFFFE = 266,338,304
> ```

Ah yes. Hence the importance of showing the values rather than some values noone knows where they are coming from.

> Also, what's the point of adding my commit to this PR if you intend to replace it with something completely different?

So that if merge your pull request should result in a void one since the commit would have been merged already.

**Comment by robUx4** [comment]
> 
> 
> Maybe I'm forgetting a rule, but wouldn't the lower limits be 0x4040, 0x202000 and 0x10100000?
> 
> As in:
> 
> ```
> Class A:       0x81 to 0xFE       =         126
> Class B:     0x4040 to 0x7FFE     =      16,319
> Class C:   0x202000 to 0x3FFFFE   =   2,088,959
> Class D: 0x10100000 to 0x1FFFFFFE = 267,386,879
> ```

It's rather the values @mkver mentioned.

**Comment by mkver** [comment]
Dave, the VINT_DATA of 0x4040 encodes the number 0x40 and 0x40 has a shorter valid encoding, namely 0xC0. Similarly for the other ranges.

**Comment by dericed** [comment]
@mkver, lol knew i was not thinking of something

**Pull request merged**
