### PR TITLE
add doctype registry to iana considerations

### PR DESCRIPTION
**Pull request by dericed**
to resolve https://github.com/Matroska-Org/ebml-specification/issues/183

### CODE REVIEW

**Comment by robUx4** [comment]
IMO one doesn't go with the other. It was never the goal to restrict the IDs from one EBML format in other EBML formats. Otherwise we'll run out of Class A IDs very quickly.

IMO for EBML we only need a registry of `DocType`, for example `"matroska"` and `"webm"` are the 2 current entries.

Then Matroska has its own IANA registry for its EBML IDs.

**Comment by dericed** [comment]
@robUx4, that comment seems more relevant to https://github.com/Matroska-Org/ebml-specification/pull/179 which was already merged. We can discuss in the call with Michael.

**Comment by robUx4** [comment]
Yes I came too late before the merge happened. But IMO it can be discussed here since you're adding a significant part that was missing.

**Comment by robUx4** [comment]
I updated the PR with the First Come First Served rule, moving it first and reserving "matroska"/"webm".

**Comment by dericed** [comment]
LGTM, I can't approve officially in github since I started the PR, but I approve here in the comments.

**Comment by mbunkus** [comment]
As we all approve and agree so much, I'll merge it.

**Pull request merged**
