### PR TITLE
Say that all-0 or all-1 vint-data must be ignored on read

### PR DESCRIPTION
**Pull request by dericed**
intended to fix
https://github.com/Matroska-Org/ebml-specification/issues/90

### CODE REVIEW

**Comment by robUx4** [comment]
I suppose it makes it forward compatible. In any case it's needed in the future, these values won't be ignored and make sense for such readers.

It doesn't say if it's valid or not though. Depending on the answer program that try to detect and fix errors in an EBML Document will have to behave differently. If the goal is that it may be used in the future (and ignored now) that means they are valid values. That would be in the same spirit of the original "reserve" state.

Should we clarify this ?

**Comment by dericed** [comment]
I think `MUST NOT be ... written` is similar to saying invalid, though we could clarify that.

**Comment by mbunkus** [comment]
I'd prefer to say that such elements are reserved in case we do want to make use of them at a later date. Requiring readers to ignore them would be enough for me.

**Comment by robUx4** [comment]
How about:
```Any `Element ID` with the `VINT_DATA` component set as all zero values or all one values MUST be ignored and MUST NOT be considered an error in the `EBML Document`.```

**Comment by dericed** [comment]
updated according to @robUx4's recommendation. please review.

**Pull request merged**
