### PR TITLE
small grammatical adjustments

### PR DESCRIPTION
**Pull request by ablwr**
Couple of small English-language adjustments ("an" instead of "a", downcasing, "cannot" instead of "can not") and backtick-ing `Element` when found capitalized. Wasn't sure if Element should be backticked or converted to lowercase. I believe it is referring to any of the identified EBML Elements, so I put it in backticks.

### CODE REVIEW

**Comment by ablwr** [comment]
These and PR #160 were the only things I could find after a careful review of the EBML Specification. 😃  🎉  🍰  🎈

**Comment by mbunkus** [comment]
This branch conflicts now that I've merged that other branch. Can you please re-base & force-push? Thanks.

**Comment by ablwr** [comment]
And I was trying to avoid the same line! Yeah, one moment.

**Comment by ablwr** [comment]
Do you want me to fumble through eliminating this merge-commit, or do you want to use the squash-and-merge option in the Merge PR dropdown?

**Comment by mbunkus** [comment]
Sure, I'll do it. Or have done it already.

**Comment by ablwr** [comment]
🎉

**Pull request merged**
