### PR TITLE
bump to version 09

### PR DESCRIPTION
**Pull request by dericed**

### CODE REVIEW

**Comment by dericed** [comment]
Been 4 months since a version bump

**Comment by retokromer** [comment]
Can https://github.com/Matroska-Org/ebml-specification/pull/200 not be resolved before?

**Comment by dericed** [comment]
@retokromer I stalled 18 hours but don't consider that #200 is blocking to the version bump

**Comment by retokromer** [comment]
It’s not a blocking issue. It would just having been «nice» to have resolved it in the new version. No more, no less.

**Comment by dericed** [comment]
Sorry @retokromer, but work is moving quickly in response to the AD review and @mcr recommended more versions rather than waiting for moments of empty PR lists.

**Pull request merged**
