### PR TITLE
Set VOID Element as multiple

### PR DESCRIPTION
**Pull request by dericed**
patch, as sent on cellar

### CODE REVIEW

**Comment by robUx4** [comment]
Could you combine #9 and #43 into one commit, since they need to be changed
together or not.

2015-12-30 14:55 GMT+01:00 Dave Rice <notifications@github.com>:

> patch, as sent on cellar
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/Matroska-Org/ebml-specification/pull/43
> Commit Summary
>
>    - Set VOID Element as multiple
>
> File Changes
>
>    - *M* specification.markdown
>    <https://github.com/Matroska-Org/ebml-specification/pull/43/files#diff-0>
>    (2)
>
> Patch Links:
>
>    - https://github.com/Matroska-Org/ebml-specification/pull/43.patch
>    - https://github.com/Matroska-Org/ebml-specification/pull/43.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Matroska-Org/ebml-specification/pull/43>.
>



-- 
Steve Lhomme
Matroska association Chairman

**Comment by dericed** [comment]
@robUx4 as noted on CELLAR, the two PRs affect separate repositories. This PR, https://github.com/Matroska-Org/ebml-specification/pull/43, updates the VOID element to multiple in the EBML specification and the other PR, https://github.com/Matroska-Org/foundation-source/pull/9, updates the VOID Element as represented in the Matroska specification.

**Comment by dericed** [comment]
anything blocking?

**Comment by mbunkus** [comment]
Nope, sorry, I overlooked this.

**Pull request merged**
